services:
  discord-bot:
    build: .
    container_name: discord-bot
    restart: unless-stopped
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./google-credentials.json
    volumes:
      - ./google-credentials.json:/app/google-credentials.json
      - ./Secrets.json:/app/Secrets.json
